version: 2

submodules:
  include: all

sphinx:
    builder: html
    configuration: docs/conf.py

python:
   version: 3.7
   install:
      - method: pip
        path: .
      - requirements: docs/requirements.txt
        

